# docker-compose.yml

version: "3.8"

services:
  # --- API Gateway Service ---
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - news-service
      - search-service

  # --- Backend Services ---
  user-service:
    build: ./services/user-service
    volumes:
      - ./services/user-service:/code
    environment:
      # Kết nối tới database riêng cho user
      - DATABASE_URL=mysql+mysqlconnector://root:password@db_user/user_db
      - JWT_SECRET_KEY=your-super-secret-key
    depends_on:
      - db_user # Phụ thuộc vào db_user

  news-service:
    build: ./services/news-service
    volumes:
      - ./services/news-service:/code
    environment:
      # Kết nối tới database riêng cho news
      - DATABASE_URL=mysql+mysqlconnector://root:password@db_news/news_db
      - JWT_SECRET_KEY=your-super-secret-key
    depends_on:
      - db_news # Phụ thuộc vào db_news

  search-service:
    build: ./services/search-service
    volumes:
      - ./services/search-service:/code

  # --- Database Services ---
  db_user: # Đổi tên db thành db_user cho rõ ràng
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=user_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306" # Port cho user DB
    volumes:
      - db-user-data:/var/lib/mysql

  db_news: # <<<<< Service database MỚI cho news-service
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=news_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306" # Expose ra một port khác trên máy host để tránh xung đột
    volumes:
      - db-news-data:/var/lib/mysql

volumes:
  db-user-data: # Volume cho user DB
  db-news-data: # Volume cho news DB
